### ISSUE TITLE
`.envrc` fails

### ISSUE THREAD

**Issue by garrison** [Qiskit-Extensions/QiskitQuantumInfo.jl#2]
Not sure if you meant to add `.envrc`, but it includes `julia_args`, which fails on my machine.  It's not part of direnv, so I'm guessing it must be part of your local configuration.

**Comment by garrison** [comment]
As I initially suspected, `julia_args` comes from https://fredrikekre.se/posts/direnv-with-julia/

I think it might make sense to remove `.envrc` since having in a public Julia repository is a bit unconventional.

**Comment by jlapeyre** [comment]
Yes you are probably correct. I didn't even know it was possible to use direnv without frederikekre 's additons.
